//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixTools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int NU_AUTO_NUM { get; set; }
        public string TX_EMAIL { get; set; }
        public string PW_PASSWORD { get; set; }
        public Nullable<int> CD_ID_STATE { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
    }
}
